# Generated by Django 4.0.3 on 2022-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.CharField(max_length=50000),
        ),
    ]
