# Generated by Django 4.0.3 on 2022-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_question_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
