# Generated by Django 4.0.3 on 2022-03-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_answernotificationmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'file')], default=0),
        ),
    ]
