# Generated by Django 4.0.3 on 2022-03-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_task_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zoom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.region'),
        ),
        migrations.CreateModel(
            name='ZoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.region')),
            ],
            options={
                'verbose_name': 'ZoomFoydalanuvchilar',
                'db_table': 'ZoomFoydalanuvchilar',
            },
        ),
    ]
