# Generated by Django 4.0.3 on 2022-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_user_zoom_alter_user_birthday_alter_user_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomuser',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
