# Generated by Django 4.0.3 on 2022-03-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_zoomuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomuser',
            name='region',
        ),
    ]
