<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-21 08:05
=======
# Generated by Django 4.0.3 on 2022-03-19 15:34
>>>>>>> 7f7093f04cdf9b6c92209daeb5d0c6ca59e5b0c8

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_zoomuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomuser',
            name='region',
        ),
    ]
